name: pull_request_checker
on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 'v20.10.0'

      - name: solve dependencies
        run: npm ci

      - name: lint
        run: npm run lint

      - name: test
        run: npm run coverage
